plugins {
    id("com.android.application")
}

android {
    namespace = "com.taobao.android.mnndemo"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.taobao.android.mnndemo"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_ARM_NEON=TRUE",
                    "-DANDROID_PLATFORM=android-21",
                    "-DANDROID_STL=c++_shared",
                    "-DMNN_JNI=TRUE",
                    "-DMNN_OPENCL=true",
                    "-DMNN_OPENGL=true",
                    "-DMNN_VULKAN=true"
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
        }
    }

    buildTypes {
        debug {}
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path = "../../../../CMakeLists.txt"
            version = "3.22.1"
        }
    }

    sourceSets {
        getByName("main") {
            jniLibs.srcDirs = ['libs']
            assets.srcDirs = ["../../../../demo/model", "../../../../resource/model"]
        }
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("com.google.android.material:material:1.11.0")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
}
