#version 450
#extension GL_EXT_scalar_block_layout : require

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) uniform Uniforms {
    float width;
    float height;
    float pad0;
    float pad1;
};

layout(set = 0, binding = 1, std430) readonly buffer InBuf {
    float in_data[];
};

layout(set = 0, binding = 2, std430) writeonly buffer OutBuf {
    float out_data[];
};

void main() {
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    int w = int(width);
    int h = int(height);

    if (int(x) >= w || int(y) >= h) return;

    int realIdx = int(x) + int(y) * w;

    float r_val = in_data[realIdx * 4 + 0];
    float g1_val = in_data[realIdx * 4 + 1];
    float g2_val = in_data[realIdx * 4 + 2];
    float b_val = in_data[realIdx * 4 + 3];

    out_data[realIdx * 4 + 0] = r_val;
    out_data[realIdx * 4 + 1] = g1_val;
    out_data[realIdx * 4 + 2] = g2_val;
    out_data[realIdx * 4 + 3] = b_val;
}
