// Auto-generated by cam-isp mnn_opset_matcher.rs — DO NOT EDIT.
// Source: CPP_FUSION_TABLE in cam-rust/cam-isp/src/mnn_opset_matcher.rs
//
// Classification:
//   Pass0   — first-match fusion (concrete const/weight checks)
//   Pass1   — guard chains (no_fuse, consumed but kept primitive)
//   Profile — structural-only matching (relaxed const checks)
#pragma once

#include <MNN/MNNDefine.h>

// ExactPattern struct — defines the five constructor overloads
// used by the static tables below (6-arg base, 7a/7b, 8a/8b).
#include "ExactPattern.h"

namespace MNN {

// ── Pass0: first-match fusion (32 entries) ─────────────────
static const ExactPattern kExactFusionTablesPass0[] = {
    // fcs_block (chain=13)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ConvolutionDepthwise, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, 1, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_SUB, nullptr),
    // tone_block (chain=12)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, 1, 0, "isp.tone", "isp.tone", MNN::BinaryOpOperation_SUB, nullptr),
    // focus_block (chain=8)
    ExactPattern({MNN::OpType_Convolution, MNN::OpType_Convolution, MNN::OpType_UnaryOp, MNN::OpType_Convolution, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_Reduction, MNN::OpType_Squeeze}, -1, -1, "isp.af_focus", "isp.af_focus", nullptr, 3),
    // yuv_sat_block (chain=7)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, 1, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_SUB, nullptr),
    // ref_yuv_sat_block (chain=6)
    ExactPattern({MNN::OpType_StridedSlice, MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_Convolution, MNN::OpType_ReLU6, MNN::OpType_Concat}, -1, -1, "isp.fcs", "isp.fcs", nullptr, 9),
    // display_conv (chain=6)
    ExactPattern({MNN::OpType_Convolution, MNN::OpType_Permute, MNN::OpType_Padding, MNN::OpType_GatherV2, MNN::OpType_BinaryOp, MNN::OpType_Cast}, -1, -1, "isp.display", "isp.display", "display", 9),
    // demosaic_ccm_2op (chain=2)
    ExactPattern({MNN::OpType_Convolution, MNN::OpType_ReLU6}, -1, -1, "isp.demosaic_ccm", "isp.demosaic_ccm", nullptr, 12),
    // ref_ccm_block (chain=2)
    ExactPattern({MNN::OpType_Convolution, MNN::OpType_BinaryOp}, -1, -1, "isp.fcs", "isp.fcs", nullptr, 9),
    // vignetting_block (chain=2)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, 1024, 1, "isp.vignetting", "isp.vignetting", MNN::BinaryOpOperation_MUL, nullptr),
    // fcs_conv (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.fcs", "isp.fcs", "fcs", 9),
    // fcs_wbgains (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 3, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_MUL, "fcs"),
    // fcs_bayer_wb (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 4, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_MUL, "fcs"),
    // demosaic_conv300 (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.demosaic_ccm", "isp.demosaic_ccm", nullptr, 300),
    // demosaic_conv36 (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.demosaic_ccm", "isp.demosaic_ccm", nullptr, 36),
    // colorspace_conv (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.colorspace", "isp.colorspace", "colorspace", 9),
    // ae_mul (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 3, 1, "isp.ae", "isp.ae", MNN::BinaryOpOperation_MUL, nullptr),
    // af_focus_conv (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.af_focus", "isp.af_focus", nullptr, 9),
    // pyramid_conv16 (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.pyramid", "isp.pyramid", nullptr, 16),
    // ccm_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.fcs", "isp.fcs", nullptr, 9),
    // cfa_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.pyramid", "isp.pyramid", nullptr, 16),
    // csc_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.colorspace", "isp.colorspace", nullptr, 9),
    // debayer_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.demosaic_debayer", "isp.demosaic_debayer", nullptr, 300),
    // demosaic_a_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.demosaic_a", "isp.demosaic_a", nullptr, 12),
    // edge_demosaic_block (chain=1)
    ExactPattern({MNN::OpType_Convolution}, -1, -1, "isp.demosaic_edge", "isp.demosaic_edge", nullptr, 108),
    // gamma_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 1, 1, "isp.gamma", "isp.gamma", MNN::BinaryOpOperation_POW, nullptr),
    // lsc_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 1024, 1, "isp.lsc", "isp.lsc", MNN::BinaryOpOperation_MUL, nullptr),
    // normalize_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 1, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_MUL, nullptr),
    // raw_blc_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 1, 1, "isp.unpack_blc", "isp.unpack_blc", MNN::BinaryOpOperation_SUB, nullptr),
    // bayer_wb_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 4, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_MUL, nullptr),
    // blc_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 4, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_SUB, nullptr),
    // wb_gains_block (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 3, 1, "isp.awb", "isp.awb", MNN::BinaryOpOperation_MUL, nullptr),
    // ee_atomic_block (chain=1)
    ExactPattern({MNN::OpType_ConvolutionDepthwise}, -1, -1, "isp.ee", "isp.ee", nullptr, 27),
};

// ── Pass1: guard chains (5 entries) ──────────────────────
static const ExactPattern kExactFusionTablesPass1[] = {
    // algo_cct (chain=21)
    ExactPattern({MNN::OpType_StridedSlice, MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.noop_cct", "isp.noop_cct", nullptr, true),
    // algo_gamma (chain=8)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.noop_gamma", "isp.noop_gamma", MNN::BinaryOpOperation_MUL, true),
    // raw_blc_2op (chain=2)
    ExactPattern({MNN::OpType_Cast, MNN::OpType_BinaryOp}, -1, -1, "isp.unpack_blc", "isp.unpack_blc", MNN::BinaryOpOperation_SUB, true),
    // normalize_guard (chain=2)
    ExactPattern({MNN::OpType_Cast, MNN::OpType_BinaryOp}, -1, -1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_REALDIV, true),
    // normalize_block_nofuse (chain=1)
    ExactPattern({MNN::OpType_BinaryOp}, 1, 1, "isp.fcs", "isp.fcs", MNN::BinaryOpOperation_REALDIV, true),
};

// ── Profile: structural-only matching (22 entries) ─────────
static const ExactPattern kExactProfileVariants[] = {
    // calibration_block (chain=21)
    ExactPattern({MNN::OpType_Reduction, MNN::OpType_Squeeze, MNN::OpType_BinaryOp, MNN::OpType_Reduction, MNN::OpType_Squeeze, MNN::OpType_Reduction, MNN::OpType_Squeeze, MNN::OpType_Reduction, MNN::OpType_Squeeze, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_Squeeze, MNN::OpType_Reduction, MNN::OpType_Reshape, MNN::OpType_Reduction, MNN::OpType_Reshape, MNN::OpType_Reduction, MNN::OpType_Reshape, MNN::OpType_Reduction, MNN::OpType_Reshape, MNN::OpType_Concat}, -1, -1, "isp.calibration", "isp.calibration", "calibration", nullptr, -1, false),
    // tone_stats_block (chain=16)
    ExactPattern({MNN::OpType_ConvertTensor, MNN::OpType_Convolution, MNN::OpType_ConvertTensor, MNN::OpType_Reduction, MNN::OpType_Reduction, MNN::OpType_Reduction, MNN::OpType_Const, MNN::OpType_BinaryOp, MNN::OpType_ConvertTensor, MNN::OpType_Reduction, MNN::OpType_Const, MNN::OpType_BinaryOp, MNN::OpType_ConvertTensor, MNN::OpType_Reduction, MNN::OpType_Size, MNN::OpType_Concat}, -1, -1, "isp.tone_stats", "isp.tone_stats", "tone_stats", nullptr, -1, false),
    // display_block (chain=16)
    ExactPattern({MNN::OpType_Permute, MNN::OpType_Padding, MNN::OpType_Shape, MNN::OpType_Rank, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_Unsqueeze, MNN::OpType_BinaryOp, MNN::OpType_Unsqueeze, MNN::OpType_StridedSlice, MNN::OpType_Squeeze, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_GatherV2, MNN::OpType_BinaryOp, MNN::OpType_Cast}, -1, -1, "isp.display", "isp.display", nullptr),
    // algo_awb_block (chain=11)
    ExactPattern({MNN::OpType_Reduction, MNN::OpType_StridedSlice, MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_Concat, MNN::OpType_Reshape}, -1, -1, "isp.awb", "isp.awb", nullptr),
    // algo_ae_block (chain=9)
    ExactPattern({MNN::OpType_StridedSlice, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6, MNN::OpType_BinaryOp, MNN::OpType_UnaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.ae", "isp.ae", nullptr),
    // ldci_block (chain=6)
    ExactPattern({MNN::OpType_Pooling, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.ldci", "isp.ldci", nullptr),
    // ee_block_legacy (chain=6)
    ExactPattern({MNN::OpType_ConvolutionDepthwise, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.ee", "isp.ee", nullptr),
    // auto_contrast_block (chain=6)
    ExactPattern({MNN::OpType_UnaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp}, -1, -1, "isp.auto_contrast", "isp.auto_contrast", nullptr),
    // warp_block (chain=6)
    ExactPattern({MNN::OpType_StridedSlice, MNN::OpType_GridSample, MNN::OpType_StridedSlice, MNN::OpType_StridedSlice, MNN::OpType_GridSample, MNN::OpType_Concat}, -1, -1, "isp.warp", "isp.warp", nullptr),
    // bilateral_block (chain=5)
    ExactPattern({MNN::OpType_ConvolutionDepthwise, MNN::OpType_ConvolutionDepthwise, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp}, -1, -1, "isp.bilateral", "isp.bilateral", nullptr),
    // local_contrast_block (chain=5)
    ExactPattern({MNN::OpType_Pooling, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.fcs", "isp.fcs", nullptr),
    // saturation_block (chain=5)
    ExactPattern({MNN::OpType_Reduction, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.fcs", "isp.fcs", nullptr),
    // unsharp_block (chain=5)
    ExactPattern({MNN::OpType_Pooling, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.fcs", "isp.fcs", nullptr),
    // display_short (chain=5)
    ExactPattern({MNN::OpType_Permute, MNN::OpType_Padding, MNN::OpType_GatherV2, MNN::OpType_BinaryOp, MNN::OpType_Cast}, -1, -1, "isp.display", "isp.display", "display"),
    // ldci_a_block (chain=4)
    ExactPattern({MNN::OpType_Pooling, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp}, -1, -1, "isp.ldci_a", "isp.ldci_a", nullptr),
    // ref_tone_block (chain=4)
    ExactPattern({MNN::OpType_Pooling, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp, MNN::OpType_BinaryOp}, -1, -1, "isp.tone", "isp.tone", nullptr),
    // ee_block (chain=3)
    ExactPattern({MNN::OpType_ConvertTensor, MNN::OpType_ConvolutionDepthwise, MNN::OpType_ConvertTensor}, -1, -1, "isp.ee", "isp.ee", nullptr),
    // unpack_blc_3op (chain=3)
    ExactPattern({MNN::OpType_Reshape, MNN::OpType_ReLU6, MNN::OpType_BinaryOp}, -1, -1, "isp.unpack_blc", "isp.unpack_blc", nullptr),
    // unpack_blc_2op (chain=2)
    ExactPattern({MNN::OpType_BinaryOp, MNN::OpType_ReLU6}, -1, -1, "isp.unpack_blc", "isp.unpack_blc", MNN::BinaryOpOperation_SUB, nullptr),
    // colorspace_matmul (chain=1)
    ExactPattern({MNN::OpType_MatMul}, -1, -1, "isp.colorspace", "isp.colorspace", nullptr),
    // downscale_interp (chain=1)
    ExactPattern({MNN::OpType_Interp}, -1, -1, "isp.interp", "isp.interp", nullptr),
    // crop_strided_slice (chain=1)
    ExactPattern({MNN::OpType_StridedSlice}, -1, -1, "isp.fcs", "isp.fcs", nullptr),
};

} // namespace MNN
